# Generated by Django 5.1.6 on 2025-02-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
