# Generated by Django 5.1.6 on 2025-02-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
