# Generated by Django 5.1.6 on 2025-02-28 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_employee_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
    ]
