# Generated by Django 5.1.6 on 2025-03-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_remove_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
