# Generated by Django 5.1.6 on 2025-03-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
