# Generated by Django 5.1.6 on 2025-03-03 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_alter_employee_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
    ]
